version: '3'

services:
    nginx:
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        container_name: nginx
        image: nginx
        ports:
            - "443:443"
        volumes:
            - wordpress_vol:/var/www/html
        networks:
            - net-work
        depends_on:
            - wordpress
        restart: on-failure

    mariadb:
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        restart: on-failure
        container_name: mariadb
        image: mariadb
        volumes:
            - mariadb_vol:/var/lib/mysql
        networks:
            - net-work
        env_file:
            - ./.env

    wordpress:
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        restart: on-failure
        container_name: wordpress
        image: wordpress
        volumes:
            - wordpress_vol:/var/www/html
        networks:
            - net-work
        depends_on:
            - mariadb
        env_file:
            - ./.env

networks:
    net-work:
        driver: bridge
  
volumes:
    mariadb_vol:
        driver: local
        driver_opts:
            type: 'none'
            device: '/home/abelhadj/data/db'
            o: 'bind'
    wordpress_vol:
        driver: local
        driver_opts:
            type: 'none'
            device: '/home/abelhadj/data/wp'
            o: 'bind'